apiVersion: v1
kind: Workflow
metadata:
  name: workflow-neo4j-basic
spec:
  label: 'Workflow Neo4j Basic'
  # autostart: true
  components:
    - name: Neo4j Reader
      type: "#Hume.Orchestra.DataSource.Neo4jReader"
      config:
        query: MATCH (n:Person) RETURN n AS data
        polling_period: 3000
      resource:
        selector:
          name: neo4j-movies
      to:
        - MessageTransformer
    - name: MessageTransformer
      type: "#Hume.Orchestra.Processor.MessageTransformer"
      config:
        transformer_script: |
          body['source'] = 'neo4j-movies'

          return body
      to:
        - Observer
    - name: Observer
      type: "#Hume.Orchestra.Monitor.Observer"
