apiVersion: v1
kind: Perspective
metadata:
  name: main-perspective
spec:
  label: Main Perspective
  access:
    - role: ANALYST
      grant_type: PERSPECTIVE_USE
    - role: INVESTIGATOR
      grant_type: PERSPECTIVE_USE
  resource:
    selector:
      name: neo4j-movies
  synced: true
  actions:
    include:
      - tag@all